
from fastapi import FastAPI, UploadFile, File, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import tempfile
import os

from services.meeting_pipeline import process_meeting
from services.assistant_service import ask_ai_assistant

from services.email_service import (
    create_email_draft,
    update_email_draft,
    approve_email_draft,
    send_email
)


# FastAPI application
app = FastAPI(
    title="CollabFlow AI Service",
    version="1.0.0"
)


# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)


# Assistant request model
class AssistantRequest(BaseModel):
    project_id: str
    question: str


# Email draft request model
class EmailDraftRequest(BaseModel):
    recipient_name: str
    recipient_email: str
    subject: str
    body: str


# Email update request model
class EmailUpdateRequest(BaseModel):
    draft: dict
    recipient_name: str | None = None
    recipient_email: str | None = None
    subject: str | None = None
    body: str | None = None


# Email approval request model
class EmailApproveRequest(BaseModel):
    draft: dict


# Email send request model
class EmailSendRequest(BaseModel):
    draft: dict


# Root endpoint
@app.get("/")
def root():
    return {
        "success": True,
        "message": "AI service is running"
    }


# AI project assistant
@app.post("/assistant")
async def project_assistant(
    request: AssistantRequest,
    authorization: str | None = Header(default=None)
):
    try:
        print("\n==========================================")
        print("AI ASSISTANT REQUEST")
        print("==========================================")

        print("Project ID:", request.project_id)
        print("Question:", request.question)

        if not request.project_id.strip():
            raise HTTPException(
                status_code=400,
                detail="Project ID is required."
            )

        if not request.question.strip():
            raise HTTPException(
                status_code=400,
                detail="Question is required."
            )

        if not authorization:
            raise HTTPException(
                status_code=401,
                detail="Authorization token is required."
            )

        if not authorization.startswith("Bearer "):
            raise HTTPException(
                status_code=401,
                detail="Invalid authorization header."
            )

        token = authorization.replace(
            "Bearer ",
            "",
            1
        ).strip()

        if not token:
            raise HTTPException(
                status_code=401,
                detail="Invalid authentication token."
            )

        result = ask_ai_assistant(
            token=token,
            project_id=request.project_id,
            question=request.question
        )

        print("\n==========================================")
        print("AI ASSISTANT RESPONSE")
        print("==========================================")

        print(
            result.get(
                "answer",
                ""
            )
        )

        if result.get("email"):
            print("Email data generated by AI.")

        print("==========================================")

        return result

    except HTTPException:
        raise

    except ValueError as error:
        print(
            "Assistant validation error:",
            str(error)
        )

        raise HTTPException(
            status_code=400,
            detail=str(error)
        )

    except Exception as error:
        print("\n==========================================")
        print("AI ASSISTANT ERROR")
        print("==========================================")

        print(
            type(error).__name__,
            ":",
            str(error)
        )

        print("==========================================")

        raise HTTPException(
            status_code=500,
            detail="AI assistant failed."
        )


# Create email draft
@app.post("/email/draft")
async def create_email_draft_endpoint(
    request: EmailDraftRequest
):
    try:
        print("\n==========================================")
        print("CREATING EMAIL DRAFT")
        print("==========================================")

        print(
            "Recipient:",
            request.recipient_email
        )

        print(
            "Subject:",
            request.subject
        )

        draft = create_email_draft(
            recipient_name=request.recipient_name,
            recipient_email=request.recipient_email,
            subject=request.subject,
            body=request.body
        )

        print(
            "Draft ID:",
            draft.get("draft_id")
        )

        print(
            "Draft created successfully."
        )

        return {
            "success": True,
            "message": "Email draft created successfully.",
            "draft": draft
        }

    except ValueError as error:
        print(
            "Email draft validation error:",
            str(error)
        )

        raise HTTPException(
            status_code=400,
            detail=str(error)
        )

    except Exception as error:
        print(
            "Email draft creation error:",
            str(error)
        )

        raise HTTPException(
            status_code=500,
            detail="Failed to create email draft."
        )


# Update email draft
@app.put("/email/draft")
async def update_email_draft_endpoint(
    request: EmailUpdateRequest
):
    try:
        print("\n==========================================")
        print("UPDATING EMAIL DRAFT")
        print("==========================================")

        updated_draft = update_email_draft(
            draft=request.draft,
            recipient_name=request.recipient_name,
            recipient_email=request.recipient_email,
            subject=request.subject,
            body=request.body
        )

        print(
            "Draft updated successfully."
        )

        return {
            "success": True,
            "message": "Email draft updated successfully.",
            "draft": updated_draft
        }

    except ValueError as error:
        print(
            "Email draft update validation error:",
            str(error)
        )

        raise HTTPException(
            status_code=400,
            detail=str(error)
        )

    except Exception as error:
        print(
            "Email draft update error:",
            str(error)
        )

        raise HTTPException(
            status_code=500,
            detail="Failed to update email draft."
        )


# Approve email draft
@app.post("/email/draft/approve")
async def approve_email_draft_endpoint(
    request: EmailApproveRequest
):
    try:
        print("\n==========================================")
        print("APPROVING EMAIL DRAFT")
        print("==========================================")

        approved_draft = approve_email_draft(
            request.draft
        )

        print(
            "Draft approved successfully."
        )

        return {
            "success": True,
            "message": "Email draft approved successfully.",
            "draft": approved_draft
        }

    except ValueError as error:
        print(
            "Email approval validation error:",
            str(error)
        )

        raise HTTPException(
            status_code=400,
            detail=str(error)
        )

    except Exception as error:
        print(
            "Email approval error:",
            str(error)
        )

        raise HTTPException(
            status_code=500,
            detail="Failed to approve email draft."
        )


# Send approved email
@app.post("/email/send")
async def send_email_endpoint(
    request: EmailSendRequest
):
    try:
        print("\n==========================================")
        print("SENDING EMAIL")
        print("==========================================")

        draft = request.draft

        if not isinstance(
            draft,
            dict
        ):
            raise HTTPException(
                status_code=400,
                detail="Invalid email draft."
            )

        if draft.get("status") != "approved":
            raise HTTPException(
                status_code=400,
                detail="Email must be approved before it can be sent."
            )

        result = send_email(
            draft
        )

        print(
            "Email sent successfully."
        )

        return {
            "success": True,
            "message": "Email sent successfully.",
            "result": result
        }

    except HTTPException:
        raise

    except ValueError as error:
        print(
            "Email sending validation error:",
            str(error)
        )

        raise HTTPException(
            status_code=400,
            detail=str(error)
        )

    except Exception as error:
        print(
            "Email sending error:",
            type(error).__name__,
            ":",
            str(error)
        )

        raise HTTPException(
            status_code=500,
            detail="Failed to send email."
        )


# Process meeting audio
@app.post("/process-meeting")
async def process_meeting_audio(
    file: UploadFile = File(...)
):
    temp_path = None

    try:
        print("\n==========================================")
        print("MEETING AUDIO RECEIVED")
        print("==========================================")

        print(
            "Filename:",
            file.filename
        )

        print(
            "Content type:",
            file.content_type
        )

        if not file.filename:
            raise HTTPException(
                status_code=400,
                detail="Audio file is required."
            )

        extension = os.path.splitext(
            file.filename
        )[1]

        if not extension:
            extension = ".webm"

        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=extension
        ) as temp_file:

            temp_path = temp_file.name

            content = await file.read()

            temp_file.write(
                content
            )

        print(
            "Temporary audio:",
            temp_path
        )

        print(
            "Audio size:",
            len(content),
            "bytes"
        )

        print("\n==========================================")
        print("STARTING MEETING AI PIPELINE")
        print("==========================================")

        result = process_meeting(
            temp_path
        )

        print("\n==========================================")
        print("MEETING AI PIPELINE COMPLETED")
        print("==========================================")

        print(
            "Total speaker turns:",
            len(result)
        )

        return {
            "success": True,
            "message": "Meeting processed successfully.",
            "segments": result
        }

    except HTTPException:
        raise

    except Exception as error:
        print("\n==========================================")
        print("MEETING PIPELINE ERROR")
        print("==========================================")

        print(
            type(error).__name__,
            ":",
            str(error)
        )

        print("==========================================")

        raise HTTPException(
            status_code=500,
            detail=str(error)
        )

    finally:
        if (
            temp_path
            and os.path.exists(temp_path)
        ):
            try:
                os.remove(
                    temp_path
                )

                print(
                    "Temporary meeting audio deleted."
                )

            except Exception as error:
                print(
                    "Could not delete temporary meeting file:",
                    str(error)
                )

